package ro.exitusro.backend.documents.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import ro.exitusro.backend.documents.DocumentEntity;

import java.time.Instant;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record DocumentSummary(
        String id,
        String type,
        String title,
        boolean signed,
        @JsonProperty("issued_at") Instant issuedAt,
        @JsonProperty("storage_path") String storagePath,
        @JsonProperty("validation_status") String validationStatus,
        @JsonProperty("validated_at") Instant validatedAt,
        @JsonProperty("validated_by") String validatedBy,
        @JsonProperty("correction_reason") String correctionReason,
        @JsonProperty("correction_requested_at") Instant correctionRequestedAt,
        @JsonProperty("auto_generated") boolean autoGenerated
) {
    public static DocumentSummary from(DocumentEntity d) {
        // Expose a URL-style identifier rather than the on-disk path so the SPA
        // never sees server filesystem layout. The actual download goes through
        // /api/documents/{id}/download-url then /content.
        String virtualPath = d.getStoragePath() != null
                ? "/api/documents/" + d.getId() + "/content"
                : null;
        boolean autoGen = d.getUploadedBy() == null
                && (d.getType().equals("cmcd") || d.getType().equals("death_certificate"));
        return new DocumentSummary(
                d.getId(),
                d.getType(),
                d.getTitle(),
                d.isSigned(),
                d.getIssuedAt(),
                virtualPath,
                d.getValidationStatus().name(),
                d.getValidatedAt(),
                d.getValidatedBy() != null ? d.getValidatedBy().getFullName() : null,
                d.getCorrectionReason(),
                d.getCorrectionRequestedAt(),
                autoGen
        );
    }
}
