/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLegalLibraryRouteImport } from './routes/_app.legal-library'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppEmergency24hRouteImport } from './routes/_app.emergency-24h'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppCasesNewRouteImport } from './routes/_app.cases.new'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalLibraryRoute = AppLegalLibraryRouteImport.update({
  id: '/legal-library',
  path: '/legal-library',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergency24hRoute = AppEmergency24hRouteImport.update({
  id: '/emergency-24h',
  path: '/emergency-24h',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesNewRoute = AppCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emergency-24h': typeof AppEmergency24hRoute
  '/inbox': typeof AppInboxRoute
  '/legal-library': typeof AppLegalLibraryRoute
  '/notifications': typeof AppNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/new': typeof AppCasesNewRoute
  '/cases/': typeof AppCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/emergency-24h': typeof AppEmergency24hRoute
  '/inbox': typeof AppInboxRoute
  '/legal-library': typeof AppLegalLibraryRoute
  '/notifications': typeof AppNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/cases/new': typeof AppCasesNewRoute
  '/cases': typeof AppCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/emergency-24h': typeof AppEmergency24hRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/legal-library': typeof AppLegalLibraryRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/cases/new': typeof AppCasesNewRoute
  '/_app/cases/': typeof AppCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/emergency-24h'
    | '/inbox'
    | '/legal-library'
    | '/notifications'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/emergency-24h'
    | '/inbox'
    | '/legal-library'
    | '/notifications'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/emergency-24h'
    | '/_app/inbox'
    | '/_app/legal-library'
    | '/_app/notifications'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_app/cases/$caseId'
    | '/_app/cases/new'
    | '/_app/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal-library': {
      id: '/_app/legal-library'
      path: '/legal-library'
      fullPath: '/legal-library'
      preLoaderRoute: typeof AppLegalLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency-24h': {
      id: '/_app/emergency-24h'
      path: '/emergency-24h'
      fullPath: '/emergency-24h'
      preLoaderRoute: typeof AppEmergency24hRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/new': {
      id: '/_app/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AppCasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEmergency24hRoute: typeof AppEmergency24hRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLegalLibraryRoute: typeof AppLegalLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesNewRoute: typeof AppCasesNewRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmergency24hRoute: AppEmergency24hRoute,
  AppInboxRoute: AppInboxRoute,
  AppLegalLibraryRoute: AppLegalLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesNewRoute: AppCasesNewRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
